import * as Yup from "yup";

export const characterFormSchema = Yup.object().shape({
  name: Yup.string().min(1).max(100).required("Required"),
  level: Yup.number().min(1).required("Required"),
  race: Yup.string().optional(),
  class: Yup.string().optional(),
  healthPoints: Yup.number().min(0).max(1000).required("Required"),
  background: Yup.string().optional(),
  stats: Yup.object().shape({
    strength: Yup.number().min(0).max(40).required("Required"),
    dexterity: Yup.number().min(0).max(40).required("Required"),
    constitution: Yup.number().min(0).max(40).required("Required"),
    intelligence: Yup.number().min(0).max(40).required("Required"),
    wisdom: Yup.number().min(0).max(40).required("Required"),
    charisma: Yup.number().min(0).max(40).required("Required"),
  }),
  skills: Yup.object().shape({
    acrobatics: Yup.number().min(-20).max(20).required("Required"),
    animalHandling: Yup.number().min(-20).max(20).required("Required"),
    arcana: Yup.number().min(-20).max(20).required("Required"),
    athletics: Yup.number().min(-20).max(20).required("Required"),
    deception: Yup.number().min(-20).max(20).required("Required"),
    history: Yup.number().min(-20).max(20).required("Required"),
    insight: Yup.number().min(-20).max(20).required("Required"),
    intimidation: Yup.number().min(-20).max(20).required("Required"),
    investigation: Yup.number().min(-20).max(20).required("Required"),
    medicine: Yup.number().min(-20).max(20).required("Required"),
    nature: Yup.number().min(-20).max(20).required("Required"),
    perception: Yup.number().min(-20).max(20).required("Required"),
    performance: Yup.number().min(-20).max(20).required("Required"),
    persuasion: Yup.number().min(-20).max(20).required("Required"),
    religion: Yup.number().min(-20).max(20).required("Required"),
    sleightOfHand: Yup.number().min(-20).max(20).required("Required"),
    stealth: Yup.number().min(-20).max(20).required("Required"),
    survival: Yup.number().min(-20).max(20).required("Required"),
  }),
  equipment: Yup.array().of(Yup.string()).optional(),
  spells: Yup.array().of(Yup.string()).optional(),
  features: Yup.array().of(Yup.string()).optional(),
  notes: Yup.string().optional(),
});
